/* Project: Relational Data Analysis Suite
Author: Luv Patel
Tools: SQLTools & SQLite Driver used for data validation.
*/

-- Task 1: Identifying the five customers with the highest lifetime spend
SELECT 
    c.first_name || ' ' || c.last_name AS customer_full_name,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_spend
FROM customers c
JOIN orders o ON c.id = o.customer_id
JOIN order_items oi ON o.id = oi.order_id
GROUP BY c.id
ORDER BY total_spend DESC
LIMIT 5;

-- TASK 2: Total revenue generated by each product category
SELECT 
    p.category,
    ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue
FROM products p
JOIN order_items oi ON p.id = oi.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;

-- TASK 3: Employees earning more than their department average
WITH DeptAverages AS (
    SELECT department_id, AVG(salary) AS avg_salary
    FROM employees
    GROUP BY department_id
)
SELECT 
    e.first_name, 
    e.last_name, 
    d.name AS department_name, 
    e.salary,
    ROUND(da.avg_salary, 2) AS department_avg
FROM employees e
JOIN departments d ON e.department_id = d.id
JOIN DeptAverages da ON e.department_id = da.department_id
WHERE e.salary > da.avg_salary
ORDER BY department_name ASC, e.salary DESC;

-- TASK 4: Number of 'Gold' loyalty customers in each city
SELECT 
    city, 
    COUNT(id) AS gold_customer_count
FROM customers
WHERE loyalty_level = 'Gold'
GROUP BY city
ORDER BY gold_customer_count DESC, city ASC;